[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_sol_a = "FEa5qGsXBBRdsp9DTnqR4ReKzjV1YLf6xqNDcQJAL7bh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
